
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.4"

[[constraint]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  revision = "70060735b3dc41c404fa5254b921d74fbcfe2687"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  revision = "4f7a7c8d696e866d06780e14b10704614a68564b"
  name = "github.com/hyperledger/fabric"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  revision = "a3647f8e31d79543b2d0f0ae2fe5c379d72cedc0"
  name = "github.com/op/go-cache"
  

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[override]]
  name = "google.golang.org/grpc"
  revision = "b3ddf786825de56a4178401b7e174ee332173b66"

################
# Downstream overrides to enable testing
# (https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependencys-version)

# Mainly downstreams that have a direct reference
[[override]]
  name = "github.com/op/go-logging"
  # TODO: source isn't picked up by parent projects - need better solution
  source = "github.com/troyronda/go-logging"   # TODO: Better home for this fork
  branch = "datarace"
  # note: go-logging is mainly a downstream package but is also in tests to ensure the fork is applied

# Temporary downstream overrides due to sirupsen/logrus case sensitivity
[[override]]
name = "github.com/docker/docker"
source = "github.com/moby/moby"
branch = "master"

[[override]]
name = "github.com/opencontainers/runc"
branch = "master"

[[override]]
  name = "github.com/Knetic/govaluate"
	revision = "3cc7c7de92e74a87c657e957e003600723db32f6"

[[override]]
  name = "github.com/Shopify/sarama"
  revision = "c01858abb625b73a3af51d0798e4ad42c8147093"

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d"

[[override]]
  name = "github.com/eapache/go-resiliency"
  revision = "b86b1ec0dd4209a588dc1285cdd471e73525c0b3"

[[override]]
  name = "github.com/eapache/go-xerial-snappy"
  revision = "bb955e01b9346ac19dc29eb16586c90ded99a98c"

[[override]]
  name = "github.com/eapache/queue"
  revision = "44cc805cf13205b55f69e14bcb69867d1ae92f98"

[[override]]
  name = "github.com/golang/groupcache"
  revision = "b710c8433bd175204919eb38776e944233235d03"

[[override]]
  name = "github.com/golang/snappy"
  revision = "d9eb7a3d35ec988b8585d4a0068e462c27d28380"

[[override]]
  name = "github.com/pierrec/lz4"
  revision = "90290f74b1b4d9c097f0a3b3c7eba2ef3875c699"

[[override]]
  name = "github.com/pierrec/xxHash"
  revision = "5a004441f897722c627870a981d02b29924215fa"

[[override]]
  name = "github.com/pmezard/go-difflib"
  revision = "792786c7400a136282c1664665ae0a8db921c6c2"

[[override]]
  name = "github.com/rcrowley/go-metrics"
  revision = "ab2277b1c5d15c3cba104e9cbddbdfc622df5ad8"

[[override]]
  name = "github.com/stretchr/testify"
  revision = "d77da356e56a7428ad25149ca77381849a6a5232"

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "6b4daa5362b502898ddf367c5c11deb9e7a5c727"

[[override]]
  name = "github.com/cloudflare/cfssl"
  revision = "7d88da830aad9d533c2fb8532da23f6a75331b52"
