# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#############################################################
# Test configuration for config
logging:
  level: debug
tls:
  caCerts:
  - |
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIQeffVJLMYJvaHEw38bqdmizANBgkqhkiG9w0BAQsFADAl
    MRQwEgYDVQQKEwtMb2cgQ291cmllcjENMAsGA1UEAxMEdGVzdDAeFw0xNzAzMDkx
    OTM0MTNaFw0xODAzMDkxOTM0MTNaMCUxFDASBgNVBAoTC0xvZyBDb3VyaWVyMQ0w
    CwYDVQQDEwR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvqBA
    zrHwYCVQ7PJt2QTzrA6Px3BKpNu2KXywyHyq+nCwwByF89a0ZZCmDQXO9v4M1KZH
    OV3meoQnm5ugxNKqATp55cG+R4KjSxZvilb8d2JtTAsoiQZIg9HeuF0lHlveoC4J
    3/w0WMfbyll2BZ3r2TwhtbOinbkMRX19uMTmrsJESze2QYDOfqLMofJOBJHpDHnE
    x+V9gfoV9A0Z3wpriMrdjgC5P80jKIpMD5THX9kymMLMSokXwPu4CUU0PS4wapAa
    yxHoGL/loYAEyyghzeoCbvQMBUfACCNyNDcw8PLeXiRtHapOimhDQyX8Ya6VRCjM
    FNb6rFuH6NXII6UkcQIDAQABo2wwajAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHREEKzApgglsb2NhbGhv
    c3SHBH8AAAGHBKwRAAGHBKwRAAKHBKwRAAOHBKwRAAUwDQYJKoZIhvcNAQELBQAD
    ggEBAD254v1sRxM8iFXdhHYLBePuKjwmRMO8CuoIw2SWO/PxC7QrndiwSwKLDS8i
    hXwfxWyZm9jQXDeDSsy+dy5GCX+4XpdDeIrjru82S4wcmjusbN6m56IzZJSZAZPu
    vJBK1V4BJq1Jqgfz16ABkVNZ0uKKsGYf28h0mdL6m9nnuF1feJJboHX9AQScNLZo
    gq9qeo9hqgAXXfb7Ft+3lkMF9ff5e4ts/v3nIM4Wc24eirwUQF0TtxS3+WaviK7Z
    PXAUjNDAXZLOPPY7mPhBAQ5eLOZn9DUiT0qigwwXORePHQ+qYnRV9RePhnqITodE
    V58+W7zyft+tPFCHR160tQMG4zA=
    -----END CERTIFICATE-----
  - |
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIQeffVJLMYJvaHEw38bqdmizANBgkqhkiG9w0BAQsFADAl
    MRQwEgYDVQQKEwtMb2cgQ291cmllcjENMAsGA1UEAxMEdGVzdDAeFw0xNzAzMDkx
    OTM0MTNaFw0xODAzMDkxOTM0MTNaMCUxFDASBgNVBAoTC0xvZyBDb3VyaWVyMQ0w
    CwYDVQQDEwR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvqBA
    zrHwYCVQ7PJt2QTzrA6Px3BKpNu2KXywyHyq+nCwwByF89a0ZZCmDQXO9v4M1KZH
    OV3meoQnm5ugxNKqATp55cG+R4KjSxZvilb8d2JtTAsoiQZIg9HeuF0lHlveoC4J
    3/w0WMfbyll2BZ3r2TwhtbOinbkMRX19uMTmrsJESze2QYDOfqLMofJOBJHpDHnE
    x+V9gfoV9A0Z3wpriMrdjgC5P80jKIpMD5THX9kymMLMSokXwPu4CUU0PS4wapAa
    yxHoGL/loYAEyyghzeoCbvQMBUfACCNyNDcw8PLeXiRtHapOimhDQyX8Ya6VRCjM
    FNb6rFuH6NXII6UkcQIDAQABo2wwajAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHREEKzApgglsb2NhbGhv
    c3SHBH8AAAGHBKwRAAGHBKwRAAKHBKwRAAOHBKwRAAUwDQYJKoZIhvcNAQELBQAD
    ggEBAD254v1sRxM8iFXdhHYLBePuKjwmRMO8CuoIw2SWO/PxC7QrndiwSwKLDS8i
    hXwfxWyZm9jQXDeDSsy+dy5GCX+4XpdDeIrjru82S4wcmjusbN6m56IzZJSZAZPu
    vJBK1V4BJq1Jqgfz16ABkVNZ0uKKsGYf28h0mdL6m9nnuF1feJJboHX9AQScNLZo
    gq9qeo9hqgAXXfb7Ft+3lkMF9ff5e4ts/v3nIM4Wc24eirwUQF0TtxS3+WaviK7Z
    PXAUjNDAXZLOPPY7mPhBAQ5eLOZn9DUiT0qigwwXORePHQ+qYnRV9RePhnqITodE
    V58+W7zyft+tPFCHR160tQMG4zA=
    -----END CERTIFICATE-----
  clientCert: |
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIQShfOPJ8TBxx8/bhBOduxvzANBgkqhkiG9w0BAQsFADAl
    MRQwEgYDVQQKEwtMb2cgQ291cmllcjENMAsGA1UEAxMEdGVzdDAeFw0xNzAzMDkx
    OTQxNDJaFw0xODAzMDkxOTQxNDJaMCUxFDASBgNVBAoTC0xvZyBDb3VyaWVyMQ0w
    CwYDVQQDEwR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4J9v
    9DlrWl+UaP0JBWCOhKXfhNHh1VghED5hHERFmfsdVSU+koCmND4r47P5K/EnCq9/
    Tt0OnV09IlC+65KRGQYMp7FiJekKx3SDuq8yYrY1NS/ZPvzoirIoXpFO1v1aml66
    od+6Mnc4iMjgW2g2+DCtplx/eRZAMMZ5qftYBWtKhEVOAdTkeHMXwRFcDwA8aI90
    lDPqYWl+X+GGcMCc3T3DqISpBrwzJYXP0myANk36Z4Csc1W0p3eRkUxQNG7sAIN4
    ScY4DESpYY0XMPkD2WQmzZDbOWNzt4qC4lAu3KIgOUeY+gJrBwd/2fiWmZArv8SQ
    P8uCHjgbl8b1ZHnK1wIDAQABo2wwajAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAww
    CgYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHREEKzApgglsb2NhbGhv
    c3SHBH8AAAGHBKwRAAGHBKwRAAKHBKwRAAOHBKwRAAQwDQYJKoZIhvcNAQELBQAD
    ggEBAGMck/K4vRidtWL2Vm95cPBaLSR1TqKtNxBYK71nLSDD6ZtkMk8IH1qKlauH
    E+gL77tdGS/B+4UdnCgW0t+E5dZvknNtevTC8zxTV/jRV1bXRT4bEydLJFRbZHdB
    bZudQuH+9m8WJN3CGDZskeNzJ1rTtPHD2lxb3nUGvH7yciFtMGZjejNoMYDDWpnu
    E8e+4go5r8PdzuqvKNeM0tTULkPubeo1YzlWLk9d1/AO11k8wIPTsapHpXyFAMPk
    xl09FqTzfCfLbh5p4Mu1ogRT0lChY0kNtkJeLy2sD9CMF6D7/R0gfjBvFZMVFe4B
    gRb92Z4Q1ngB9HZ1Owyb4RnSbyo=
    -----END CERTIFICATE-----
  clientKey: |
     -----BEGIN RSA PRIVATE KEY-----
     MIIEpQIBAAKCAQEA4J9v9DlrWl+UaP0JBWCOhKXfhNHh1VghED5hHERFmfsdVSU+
     koCmND4r47P5K/EnCq9/Tt0OnV09IlC+65KRGQYMp7FiJekKx3SDuq8yYrY1NS/Z
     PvzoirIoXpFO1v1aml66od+6Mnc4iMjgW2g2+DCtplx/eRZAMMZ5qftYBWtKhEVO
     AdTkeHMXwRFcDwA8aI90lDPqYWl+X+GGcMCc3T3DqISpBrwzJYXP0myANk36Z4Cs
     c1W0p3eRkUxQNG7sAIN4ScY4DESpYY0XMPkD2WQmzZDbOWNzt4qC4lAu3KIgOUeY
     +gJrBwd/2fiWmZArv8SQP8uCHjgbl8b1ZHnK1wIDAQABAoIBAH2D+h4hW8CTOi30
     fu73RowO2Diywxvg9BDMmp0d9TqW3IwwlKdupfD5cLL7ZVfNmEBbUqsx0THT4Q5k
     ylp+ev/dpoKqFysR7skHbXiK33/TSyYeR6nvzs15wh8d2U0/Izqxhl5f0v7SKdAd
     V2kcceL76HzWoRB7g4D91wxJ+6SChB2ESlij4cun2aKL9AEXiS1PQ7TuIUkpRfYk
     HPzb3x0utH6h1Hkv5WbiTILgJ1Sg0X8U7YIiXD02gy8skhPWOhFa/TtiKrNjCWPX
     E+11gcSv6LseI7pBnoqHVuHy7V4pKQL66DL+gSSAfmhRFIey2mEvybL0mOOo4pVn
     Pm0rGVECgYEA/iUHMwOrr9qpcSvf8e3U8cL2cqDl3J9TZTNNXCAACEtzoPNL0jYT
     uhdG4ynvkgjFA2emevIZaIYlvBGz927dfjJ/E2BOB99LVSfsnBjhx9T709rv1xZZ
     DVK6S0tddPViyRASIB6KOXRyTM9ADGGQLEHzol866NVX6+ueP768o3kCgYEA4kM8
     WEPnYTSFFesIVZrl+L84zAKZ7zNV/ancyC7CIedOUliRPZUovrCWvl9nh+wIYyL0
     rSVTNa/CpO/7xW/FcGh8g+fGZcg6dExqBO++0t1Ip22WEfC9ys/IfyniIOMZLZD9
     ozTjKy7mhVJZb1WxbIlQeqd4nYh6IwgXtbUbfM8CgYEA4BRV3K0H2+24KIi+09kX
     QHLeSQOEqJnyNfCd7PRqEuYz9V2PJLF5g0Kyxehbyy7gRrhFGXIM5RQigUg6nZeq
     w3JSiQsIwfgnu9WP0bI+oKsxvwHzJnoV2qFukKTKqi0SBKWe1aMXzMDXZtH1bvU2
     4U7lOe0tS82Pz/vXc+0A9kECgYEAwqw8yGisNGteskwFYLokcc/9CzKVxUPzEYxL
     pITujQMZ1SnU1Rp38xG2sVcemcjQMpPJ1wuNO1zc6NJ+WhJf2uZbc5ZAkiQjfxqc
     AWFRWtX/g+Z6vzbV5SC/jgG4SLl8WUMtp3WCmw4AUudWgb9GJ29BqjZbRZc+FtQI
     qlOHsesCgYEAyKK1RowZL/ext4g2FwD6YWZ82TUXRBCNJbyGPulNY3dEIWnksXZG
     WoKqJLv0mkDgqJQYOCR17dZrbtveT22mdlhwpN2CqbkoZIZsnjZoT0QcqairSYUG
     N2jk1jOKcR/MDOQEAUxcsA3C/Q7xA81YQovFzeR2p/p/cRRbxdnvkGw=
     -----END RSA PRIVATE KEY-----
  namedClientOverride:
   abc:
     ca: |
      -----BEGIN CERTIFICATE-----
      MIIDQDCCAiigAwIBAgIQeffVJLMYJvaHEw38bqdmizANBgkqhkiG9w0BAQsFADAl
      MRQwEgYDVQQKEwtMb2cgQ291cmllcjENMAsGA1UEAxMEdGVzdDAeFw0xNzAzMDkx
      OTM0MTNaFw0xODAzMDkxOTM0MTNaMCUxFDASBgNVBAoTC0xvZyBDb3VyaWVyMQ0w
      CwYDVQQDEwR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvqBA
      zrHwYCVQ7PJt2QTzrA6Px3BKpNu2KXywyHyq+nCwwByF89a0ZZCmDQXO9v4M1KZH
      OV3meoQnm5ugxNKqATp55cG+R4KjSxZvilb8d2JtTAsoiQZIg9HeuF0lHlveoC4J
      3/w0WMfbyll2BZ3r2TwhtbOinbkMRX19uMTmrsJESze2QYDOfqLMofJOBJHpDHnE
      x+V9gfoV9A0Z3wpriMrdjgC5P80jKIpMD5THX9kymMLMSokXwPu4CUU0PS4wapAa
      yxHoGL/loYAEyyghzeoCbvQMBUfACCNyNDcw8PLeXiRtHapOimhDQyX8Ya6VRCjM
      FNb6rFuH6NXII6UkcQIDAQABo2wwajAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAww
      CgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHREEKzApgglsb2NhbGhv
      c3SHBH8AAAGHBKwRAAGHBKwRAAKHBKwRAAOHBKwRAAUwDQYJKoZIhvcNAQELBQAD
      ggEBAD254v1sRxM8iFXdhHYLBePuKjwmRMO8CuoIw2SWO/PxC7QrndiwSwKLDS8i
      hXwfxWyZm9jQXDeDSsy+dy5GCX+4XpdDeIrjru82S4wcmjusbN6m56IzZJSZAZPu
      vJBK1V4BJq1Jqgfz16ABkVNZ0uKKsGYf28h0mdL6m9nnuF1feJJboHX9AQScNLZo
      gq9qeo9hqgAXXfb7Ft+3lkMF9ff5e4ts/v3nIM4Wc24eirwUQF0TtxS3+WaviK7Z
      PXAUjNDAXZLOPPY7mPhBAQ5eLOZn9DUiT0qigwwXORePHQ+qYnRV9RePhnqITodE
      V58+W7zyft+tPFCHR160tQMG4zA=
      -----END CERTIFICATE-----
     crt: |
       -----BEGIN CERTIFICATE-----
       MIIDQDCCAiigAwIBAgIQShfOPJ8TBxx8/bhBOduxvzANBgkqhkiG9w0BAQsFADAl
       MRQwEgYDVQQKEwtMb2cgQ291cmllcjENMAsGA1UEAxMEdGVzdDAeFw0xNzAzMDkx
       OTQxNDJaFw0xODAzMDkxOTQxNDJaMCUxFDASBgNVBAoTC0xvZyBDb3VyaWVyMQ0w
       CwYDVQQDEwR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4J9v
       9DlrWl+UaP0JBWCOhKXfhNHh1VghED5hHERFmfsdVSU+koCmND4r47P5K/EnCq9/
       Tt0OnV09IlC+65KRGQYMp7FiJekKx3SDuq8yYrY1NS/ZPvzoirIoXpFO1v1aml66
       od+6Mnc4iMjgW2g2+DCtplx/eRZAMMZ5qftYBWtKhEVOAdTkeHMXwRFcDwA8aI90
       lDPqYWl+X+GGcMCc3T3DqISpBrwzJYXP0myANk36Z4Csc1W0p3eRkUxQNG7sAIN4
       ScY4DESpYY0XMPkD2WQmzZDbOWNzt4qC4lAu3KIgOUeY+gJrBwd/2fiWmZArv8SQ
       P8uCHjgbl8b1ZHnK1wIDAQABo2wwajAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAww
       CgYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHREEKzApgglsb2NhbGhv
       c3SHBH8AAAGHBKwRAAGHBKwRAAKHBKwRAAOHBKwRAAQwDQYJKoZIhvcNAQELBQAD
       ggEBAGMck/K4vRidtWL2Vm95cPBaLSR1TqKtNxBYK71nLSDD6ZtkMk8IH1qKlauH
       E+gL77tdGS/B+4UdnCgW0t+E5dZvknNtevTC8zxTV/jRV1bXRT4bEydLJFRbZHdB
       bZudQuH+9m8WJN3CGDZskeNzJ1rTtPHD2lxb3nUGvH7yciFtMGZjejNoMYDDWpnu
       E8e+4go5r8PdzuqvKNeM0tTULkPubeo1YzlWLk9d1/AO11k8wIPTsapHpXyFAMPk
       xl09FqTzfCfLbh5p4Mu1ogRT0lChY0kNtkJeLy2sD9CMF6D7/R0gfjBvFZMVFe4B
       gRb92Z4Q1ngB9HZ1Owyb4RnSbyo=
       -----END CERTIFICATE-----
     key: |
       -----BEGIN RSA PRIVATE KEY-----
       MIIEpQIBAAKCAQEA4J9v9DlrWl+UaP0JBWCOhKXfhNHh1VghED5hHERFmfsdVSU+
       koCmND4r47P5K/EnCq9/Tt0OnV09IlC+65KRGQYMp7FiJekKx3SDuq8yYrY1NS/Z
       PvzoirIoXpFO1v1aml66od+6Mnc4iMjgW2g2+DCtplx/eRZAMMZ5qftYBWtKhEVO
       AdTkeHMXwRFcDwA8aI90lDPqYWl+X+GGcMCc3T3DqISpBrwzJYXP0myANk36Z4Cs
       c1W0p3eRkUxQNG7sAIN4ScY4DESpYY0XMPkD2WQmzZDbOWNzt4qC4lAu3KIgOUeY
       +gJrBwd/2fiWmZArv8SQP8uCHjgbl8b1ZHnK1wIDAQABAoIBAH2D+h4hW8CTOi30
       fu73RowO2Diywxvg9BDMmp0d9TqW3IwwlKdupfD5cLL7ZVfNmEBbUqsx0THT4Q5k
       ylp+ev/dpoKqFysR7skHbXiK33/TSyYeR6nvzs15wh8d2U0/Izqxhl5f0v7SKdAd
       V2kcceL76HzWoRB7g4D91wxJ+6SChB2ESlij4cun2aKL9AEXiS1PQ7TuIUkpRfYk
       HPzb3x0utH6h1Hkv5WbiTILgJ1Sg0X8U7YIiXD02gy8skhPWOhFa/TtiKrNjCWPX
       E+11gcSv6LseI7pBnoqHVuHy7V4pKQL66DL+gSSAfmhRFIey2mEvybL0mOOo4pVn
       Pm0rGVECgYEA/iUHMwOrr9qpcSvf8e3U8cL2cqDl3J9TZTNNXCAACEtzoPNL0jYT
       uhdG4ynvkgjFA2emevIZaIYlvBGz927dfjJ/E2BOB99LVSfsnBjhx9T709rv1xZZ
       DVK6S0tddPViyRASIB6KOXRyTM9ADGGQLEHzol866NVX6+ueP768o3kCgYEA4kM8
       WEPnYTSFFesIVZrl+L84zAKZ7zNV/ancyC7CIedOUliRPZUovrCWvl9nh+wIYyL0
       rSVTNa/CpO/7xW/FcGh8g+fGZcg6dExqBO++0t1Ip22WEfC9ys/IfyniIOMZLZD9
       ozTjKy7mhVJZb1WxbIlQeqd4nYh6IwgXtbUbfM8CgYEA4BRV3K0H2+24KIi+09kX
       QHLeSQOEqJnyNfCd7PRqEuYz9V2PJLF5g0Kyxehbyy7gRrhFGXIM5RQigUg6nZeq
       w3JSiQsIwfgnu9WP0bI+oKsxvwHzJnoV2qFukKTKqi0SBKWe1aMXzMDXZtH1bvU2
       4U7lOe0tS82Pz/vXc+0A9kECgYEAwqw8yGisNGteskwFYLokcc/9CzKVxUPzEYxL
       pITujQMZ1SnU1Rp38xG2sVcemcjQMpPJ1wuNO1zc6NJ+WhJf2uZbc5ZAkiQjfxqc
       AWFRWtX/g+Z6vzbV5SC/jgG4SLl8WUMtp3WCmw4AUudWgb9GJ29BqjZbRZc+FtQI
       qlOHsesCgYEAyKK1RowZL/ext4g2FwD6YWZ82TUXRBCNJbyGPulNY3dEIWnksXZG
       WoKqJLv0mkDgqJQYOCR17dZrbtveT22mdlhwpN2CqbkoZIZsnjZoT0QcqairSYUG
       N2jk1jOKcR/MDOQEAUxcsA3C/Q7xA81YQovFzeR2p/p/cRRbxdnvkGw=
       -----END RSA PRIVATE KEY-----
schemas:
  - type: application/json
    request: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Request Schema",
    "description": "Some product",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier for a product",
            "type": "string"
        },
        "name": {
            "description": "Name of the product",
            "type": "string"
        },
        "story": {
            "description": "Product story",
            "type": "string"
        }
    },
    "required": ["id", "name"]
}'
    response: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Response Schema",
    "description": "Some description",
    "type": "object",
    "properties": {
        "response": {
            "description": "Response description",
            "type": "string"
        }
    },
    "required": ["description"]
}'