# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
eventsnap:

    eventhub:
        # registration timeout
        regtimeout: 1s

    relay:
        # event relay timeout
        timeout: 1s

        tlsCerts:
            # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
            systemCertPool: false

            # [Optional]. Client key and cert for TLS handshake with peers and orderers
            client:
                keyfile: tls/client_sdk_go-key.pem
                certfile: tls/client_sdk_go.pem

    dispatcher:
        # total number of events that could be buffered without blocking send
        buffersize: 100

    consumer:
        # total number of events that could be buffered without blocking send
        buffersize: 100

        # timeout duration for producer to send an event to the consumer.
        # if < 0, if buffer full, unblocks immediately and not send
        # if 0, if buffer full, will block and guarantee the event will be sent out
        # if > 0, if buffer full, blocks till timeout
        timeout: 10ms
